#!/usr/bin/env python3
"""
generate_wiki_moc.py - generate a Claude-readable map-of-content per wiki.

research-os's root index.md is Dataview-driven: it renders for the human in
Obsidian but is invisible to Claude at read time. This writes a plain-markdown
`_map.md` at each wiki root (and an aggregate at the vault root) that /wiki-pull
and agents read FIRST as a fast catalog before scanning folders.

Generated file - never hand-edit; re-run to refresh. Stdlib-only. Reuses the
frontmatter parser and registry resolution from wiki_quality_check.py.

Usage:
    python generate_wiki_moc.py --root  <path/to/vault/root>
    python generate_wiki_moc.py --vault <path/to/one/wiki>

Always exits 0 - it is a generator, not a gate.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from wiki_quality_check import parse_frontmatter, resolve_root_wikis  # noqa: E402

# Numbered folders whose notes belong in the catalog (raw sources / inbox excluded).
CATALOG_FOLDERS: tuple[tuple[str, str], ...] = (
    ("20_summaries", "Source summaries"),
    ("30_concepts", "Concepts"),
    ("40_methods", "Methods"),
    ("50_datasets", "Datasets"),
    ("60_people_institutions", "People & institutions"),
    ("90_synthesis", "Synthesis"),
)

GENERATED_HEADER = "<!-- @generated by generate_wiki_moc.py - do not hand-edit; re-run to refresh -->"

MAX_LEDE_CHARS = 200


def first_sentence(summary: str) -> str:
    """A compact one-line lede: the first sentence, or a trimmed prefix."""
    s = " ".join(summary.split())
    if not s:
        return ""
    for i, ch in enumerate(s):
        if ch in ".!?" and i >= 40:
            return s[: i + 1]
    return s if len(s) <= MAX_LEDE_CHARS else s[:MAX_LEDE_CHARS].rstrip() + "..."


def entry_line(md_path: Path) -> str | None:
    try:
        text = md_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    frontmatter, _ = parse_frontmatter(text)
    stem = md_path.stem
    title = frontmatter.get("title")
    title = title if isinstance(title, str) and title.strip() else stem
    summary = frontmatter.get("summary")
    lede = first_sentence(summary) if isinstance(summary, str) else ""
    label = f"[[{stem}|{title}]]"
    return f"- {label}" + (f" - {lede}" if lede else "")


def build_wiki_moc(wiki_root: Path) -> str:
    lines: list[str] = [
        GENERATED_HEADER,
        "",
        f"# {wiki_root.name} - map",
        "",
        "A flat catalog of this wiki's durable pages, read first as a fast index. "
        "Regenerated by `generate_wiki_moc.py` (via `/wiki-maintain`).",
    ]
    for folder, heading in CATALOG_FOLDERS:
        folder_path = wiki_root / folder
        if not folder_path.is_dir():
            continue
        entries = [
            line
            for md_path in sorted(folder_path.glob("*.md"))
            if md_path.name.lower() != "readme.md"
            for line in (entry_line(md_path),)
            if line
        ]
        if not entries:
            continue
        lines.append("")
        lines.append(f"## {heading} ({len(entries)})")
        lines.extend(entries)
    lines.append("")
    return "\n".join(lines)


def write_wiki_moc(wiki_root: Path) -> Path:
    out_path = wiki_root / "_map.md"
    out_path.write_text(build_wiki_moc(wiki_root), encoding="utf-8")
    return out_path


def build_root_moc(wiki_paths: list[Path]) -> str:
    lines: list[str] = [
        GENERATED_HEADER,
        "",
        "# Vault map",
        "",
        "Registered thematic wikis. Open each wiki's `_map.md` for its full catalog.",
        "",
    ]
    for wiki in sorted(wiki_paths):
        lines.append(f"- **{wiki.name}** - [[{wiki.name}/_map|map]]")
    lines.append("")
    lines.append("Personal layer: `_brain/` (see `_brain/README.md`).")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    parser = argparse.ArgumentParser(
        description="Generate a Claude-readable _map.md per wiki. Always exits 0.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--vault", type=str, help="Path to a single wiki folder.")
    group.add_argument("--root", type=str, help="Path to the vault root; maps every registered wiki.")
    args = parser.parse_args(argv)

    if args.vault:
        wiki_path = Path(args.vault).expanduser().resolve()
        if not wiki_path.is_dir():
            print(f"'{wiki_path}' is not a directory - nothing to map.")
            return 0
        print(f"Wrote {write_wiki_moc(wiki_path)}")
        return 0

    root_path = Path(args.root).expanduser().resolve()
    wiki_paths = [p for p in resolve_root_wikis(root_path) if p.is_dir()]
    if not wiki_paths:
        print("No registered wikis found (checked ~/.claude/vaults.json, then scanned the root).")
        return 0
    for wiki in wiki_paths:
        print(f"Wrote {write_wiki_moc(wiki)}")
    root_out = root_path / "_map.md"
    root_out.write_text(build_root_moc(wiki_paths), encoding="utf-8")
    print(f"Wrote {root_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
